In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ -1.28007788 -14.26283466 -13.89789743 ...   0.54805109  -5.81762108
    7.30327946]
 [ -1.19071454 -10.01778037  10.28166984 ... -16.46666851   3.13987861
   -4.24872159]
 [ -7.50734084  26.89777697  14.28955038 ... -11.79100572   3.15676547
    1.91508187]
 ...
 [  8.64797776  -4.12127804  -2.60551269 ...   3.94319596  -2.77655596
   13.73452679]
 [ 11.90033859  11.17918259   8.48681827 ...  -1.20057289  -9.98776258
   -0.33040447]
 [-10.71184234   9.9194316   -4.58470826 ...   9.79699353  -9.04096337
    8.5819028 ]]


In [5]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m) / std)
print(X_norm)

[[-0.28657769 -1.50201908 -1.48330833 ...  0.0075628  -0.69832767
   0.70103914]
 [-0.27753262 -1.08077735  0.9136095  ... -1.65543137  0.19237048
  -0.50855121]
 [-0.91688109  2.58239676  1.31091025 ... -1.19843883  0.19404964
   0.13685015]
 ...
 [ 0.71830797 -0.4956605  -0.36389548 ...  0.33939936 -0.39593624
   1.3744441 ]
 [ 1.04750141  1.02262218  0.73568606 ... -0.16334519 -1.11298995
  -0.0982709 ]
 [-1.24123036  0.89761561 -0.56009292 ...  0.9115411  -1.018844
   0.83492162]]


In [6]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [10]:
A = np.eye(3)
B = np.eye(3)
AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
